const resources=[
{id:'orbkit',name:'Orbkit',category:'Components',subcategory:'Animation',tags:['Shaders','React'],access:['Free'],url:'https://orbkit.zzzzshawn.cloud/'},
{id:'grainient',name:'Grainient',category:'Backgrounds',subcategory:'Gradients',tags:['Textures','Gradients'],access:['Free','Paid'],url:'https://grainient.supply/collections'},
{id:'shadcn',name:'shadcn/ui',category:'UI libraries',subcategory:'React',tags:['React','Components'],access:['Free'],url:'https://ui.shadcn.com/'},
{id:'reactbits',name:'React Bits',category:'Components',subcategory:'Animation',tags:['React','Motion'],access:['Free','Paid'],url:'https://reactbits.dev/'},
{id:'lucide',name:'Lucide',category:'Icons',subcategory:'Outline',tags:['SVG','Open source'],access:['Free'],url:'https://lucide.dev/'},
{id:'built',name:'Built by Designers',category:'Inspiration',subcategory:'Directories',tags:['Websites','Tools'],access:['Free'],url:'https://builtbydesigners.com/'}];
const categories=[{name:'Components',icon:'layers',sub:['Animation','Buttons','Navigation']},{name:'UI libraries',icon:'box',sub:['React','Vue','CSS']},{name:'Icons',icon:'shapes',sub:['Outline','Solid','3D']},{name:'Backgrounds',icon:'image',sub:['Gradients','Textures','Shaders']},{name:'Inspiration',icon:'lightbulb',sub:['Directories','Landing pages','Portfolios']}];
const $=s=>document.querySelector(s);let state={page:'all',category:null,sub:null,price:'All'},favourites=new Set;try{favourites=new Set(JSON.parse(localStorage.getItem('uilist-favourites')||'[]'));if(localStorage.getItem('uilist-theme')==='light')document.documentElement.classList.add('light')}catch{}
const icon=n=>`<i class="icon-${n}" aria-hidden="true"></i>`;
$('#categories').innerHTML=categories.map((c,i)=>`<section class="sidebar-section" data-section="${c.name}"><button class="nav-item category-trigger" data-category="${c.name}" aria-label="${c.name}" title="${c.name}" aria-expanded="false" aria-controls="sub-${i}" aria-pressed="false">${icon(c.icon)}<span>${c.name}</span><small>${resources.filter(r=>r.category===c.name).length}</small>${icon('chevron-right')}</button><div class="submenu-motion" id="sub-${i}" inert><div class="submenu-inner"><div class="subcategories">${c.sub.map(sub=>`<button data-sub="${sub}" data-parent="${c.name}" aria-pressed="false"><span>${sub}</span><small>${resources.filter(r=>r.category===c.name&&(r.subcategory===sub||r.tags.includes(sub))).length}</small></button>`).join('')}</div></div></div></section>`).join('');
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function render(){const q=$('#search').value.trim().toLowerCase();const shown=resources.filter(r=>(state.page!=='saved'||favourites.has(r.id))&&(!state.category||r.category===state.category)&&(!state.sub||r.subcategory===state.sub||r.tags.includes(state.sub))&&(state.price==='All'||r.access.includes(state.price))&&[r.name,r.category,r.subcategory,...r.tags].join(' ').toLowerCase().includes(q));$('#grid').innerHTML=shown.map(r=>`<article class="card"><a class="preview-link" href="${r.url}" target="_blank" rel="noopener noreferrer" aria-label="Visit ${r.name}"><img class="preview" src="assets/${r.id}.png" alt="${r.name} website preview"></a><div class="card-heading"><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.name}</a><button class="save ${favourites.has(r.id)?'saved':''}" data-save="${r.id}" aria-label="${favourites.has(r.id)?'Remove':'Save'} ${r.name}${favourites.has(r.id)?' from':' to'} favourites" aria-pressed="${favourites.has(r.id)}">${icon(favourites.has(r.id)?'bookmark-check':'bookmark')}</button></div><div class="metadata"><button data-category="${r.category}">${r.category}</button><span class="dot"></span><span title="${r.access.join(' and ')} options">${r.access.length>1?'Free + Paid':r.access[0]}</span></div></article>`).join('');$('#all-count').textContent=resources.length;$('#saved-count').textContent=favourites.size;$('#title').textContent=state.sub||state.category||(state.page==='saved'?'Favourites':'All websites');$('#subtitle').textContent=state.page==='saved'?'The good ones, kept close.':state.sub?`${state.category}, a little more specific.`:'Good tools. Great interfaces.';$('#result-count').textContent=`${shown.length} website${shown.length===1?'':'s'}`;$('#empty').hidden=shown.length>0;$('#empty-description').textContent=state.page==='saved'&&!favourites.size?'Tap the bookmark on any website to keep it here.':'Try a different search, category, or pricing filter.';$('#clear').hidden=!q&&!state.category&&state.price==='All';document.querySelectorAll('[data-price]').forEach(b=>{b.classList.toggle('selected',b.dataset.price===state.price);b.setAttribute('aria-pressed',b.dataset.price===state.price)});document.querySelectorAll('[data-page]').forEach(b=>{const active=b.dataset.page===state.page&&!state.category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});document.querySelectorAll('#categories [data-category]').forEach(b=>{b.classList.toggle('active',b.dataset.category===state.category);b.setAttribute('aria-pressed',b.dataset.category===state.category)});document.querySelectorAll('[data-sub]').forEach(b=>{const active=b.dataset.sub===state.sub&&b.dataset.parent===state.category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)})}
function reset(){state={page:'all',category:null,sub:null,price:'All'};$('#search').value='';render()}
document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;favourites.has(id)?favourites.delete(id):favourites.add(id);try{localStorage.setItem('uilist-favourites',JSON.stringify([...favourites]))}catch{notify('Saved for this visit. Browser storage is unavailable.')}render();return}const sub=e.target.closest('[data-sub]');if(sub){state.category=sub.dataset.parent;state.sub=sub.dataset.sub;render();closeMobileSidebar();return}const cat=e.target.closest('[data-category]');if(cat){e.preventDefault();state.category=cat.dataset.category;state.sub=null;const section=cat.closest('.sidebar-section');if(section){if(sidebarCollapsed&&!mobileQuery.matches)setCollapsed(false);toggleSection(section)}else{closeMobileSidebar()}render();return}const page=e.target.closest('[data-page]');if(page){state.page=page.dataset.page;state.category=null;state.sub=null;render();closeMobileSidebar();return}const price=e.target.closest('[data-price]');if(price){state.price=price.dataset.price;render()}});$('#search').oninput=render;$('#clear').onclick=()=>{state.category=null;state.sub=null;state.price='All';$('#search').value='';render()};$('#empty-reset').onclick=reset;$('#explore').onclick=reset;
function themeLabel(){const light=document.documentElement.classList.contains('light');$('#theme').innerHTML=icon(light?'moon':'sun');$('#theme').setAttribute('aria-label',`Switch to ${light?'dark':'light'} theme`)}$('#theme').onclick=()=>{document.documentElement.classList.toggle('light');try{localStorage.setItem('uilist-theme',document.documentElement.classList.contains('light')?'light':'dark')}catch{}themeLabel()};themeLabel();const mobileQuery=window.matchMedia('(max-width:650px)');let sidebarCollapsed=false, mobileReturnFocus=null;
try{sidebarCollapsed=localStorage.getItem('uilist-sidebar-collapsed')==='true'}catch{}
const sidebar=$('#sidebar'),sidebarTrigger=$('.mobile-menu');
function toggleSection(section){const opening=!section.classList.contains('section-open');document.querySelectorAll('.sidebar-section').forEach(el=>{const open=el===section&&opening;el.classList.toggle('section-open',open);el.querySelector('.category-trigger').setAttribute('aria-expanded',open);el.querySelector('.submenu-motion').inert=!open})}
function setCollapsed(collapsed){sidebarCollapsed=collapsed;document.body.classList.toggle('sidebar-collapsed',collapsed&&!mobileQuery.matches);try{localStorage.setItem('uilist-sidebar-collapsed',String(collapsed))}catch{}syncSidebar()}
function syncSidebar(){const mobile=mobileQuery.matches,open=document.body.classList.contains('sidebar-open');document.body.classList.toggle('sidebar-collapsed',sidebarCollapsed&&!mobile);sidebarTrigger.setAttribute('aria-expanded',mobile?open:!sidebarCollapsed);sidebarTrigger.setAttribute('aria-label',mobile?'Open navigation':sidebarCollapsed?'Expand sidebar':'Collapse sidebar');$('.sidebar-rail').setAttribute('aria-label',sidebarCollapsed?'Expand sidebar':'Collapse sidebar');$('.sidebar-rail').title=(sidebarCollapsed?'Expand':'Collapse')+' sidebar (⌘B)';sidebar.inert=mobile&&!open;document.querySelectorAll('.submenu-motion').forEach(el=>el.inert=!el.closest('.sidebar-section').classList.contains('section-open')||(!mobile&&sidebarCollapsed));if(mobile&&open){sidebar.setAttribute('role','dialog');sidebar.setAttribute('aria-modal','true')}else{sidebar.removeAttribute('role');sidebar.removeAttribute('aria-modal')}}
function openMobileSidebar(){if(!mobileQuery.matches)return;mobileReturnFocus=document.activeElement;document.body.classList.add('sidebar-open');$('#sidebar-backdrop').hidden=false;$('main').inert=true;document.body.style.overflow='hidden';syncSidebar();requestAnimationFrame(()=>{if(document.body.classList.contains('sidebar-open'))$('.sidebar-close').focus()})}
function closeMobileSidebar(){if(!document.body.classList.contains('sidebar-open'))return;document.body.classList.remove('sidebar-open');$('#sidebar-backdrop').hidden=true;$('main').inert=false;document.body.style.overflow='';syncSidebar();if(mobileReturnFocus?.isConnected)mobileReturnFocus.focus();mobileReturnFocus=null}
sidebarTrigger.onclick=()=>mobileQuery.matches?openMobileSidebar():setCollapsed(!sidebarCollapsed);$('.sidebar-rail').onclick=()=>setCollapsed(!sidebarCollapsed);$('.sidebar-close').onclick=closeMobileSidebar;$('#sidebar-backdrop').onclick=closeMobileSidebar;
mobileQuery.addEventListener('change',()=>{closeMobileSidebar();syncSidebar()});
document.querySelectorAll('.library .nav-item').forEach(b=>{b.setAttribute('aria-label',b.querySelector('span').textContent);b.title=b.querySelector('span').textContent});$('#submit').title='Submit a website';$('#submit').setAttribute('aria-label','Submit a website');
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||document.activeElement.isContentEditable;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='b'&&!typing&&!$('#dialog').open){e.preventDefault();mobileQuery.matches?(document.body.classList.contains('sidebar-open')?closeMobileSidebar():openMobileSidebar()):setCollapsed(!sidebarCollapsed)}if(e.key==='/'&&!typing&&!$('#dialog').open&&!document.body.classList.contains('sidebar-open')){e.preventDefault();$('#search').focus()}if(e.key==='Escape'&&!$('#dialog').open)closeMobileSidebar();if(e.key==='Tab'&&mobileQuery.matches&&document.body.classList.contains('sidebar-open')&&!$('#dialog').open){const focusable=[...sidebar.querySelectorAll('a[href],button:not([disabled])')].filter(el=>!el.closest('[inert]')&&el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden');const first=focusable[0],last=focusable.at(-1);if(!sidebar.contains(document.activeElement)){e.preventDefault();first.focus()}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});syncSidebar();
const dialog=$('#dialog'),content=$('#dialog-content');$('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};$('#about').onclick=()=>{content.innerHTML='<h2>Good tools.<br>Great interfaces.</h2><p>UILIST is a small, curated collection of websites for people who design and build. Explore components, libraries, icons, backgrounds, and fresh inspiration.</p><p>Save your favourites and find them here next time. Your favourites stay in this browser.</p>';dialog.showModal()};$('#collections').onclick=()=>{content.innerHTML='<h2>A good place to start.</h2><p>Explore a few useful corners of the collection.</p>'+categories.map(c=>`<button class="collection" data-collection="${c.name}"><span>${c.name}<small>${resources.filter(r=>r.category===c.name).length} websites</small></span>${icon('arrow-up-right')}</button>`).join('');dialog.showModal();content.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{state={page:'all',category:b.dataset.collection,sub:null,price:'All'};$('#search').value='';render();dialog.close()})};$('#submit').onclick=()=>{closeMobileSidebar();content.innerHTML='<h2>Found something good?</h2><p>Keep a suggestion for the collection.</p><form id="submission"><label for="resource-name">Website name</label><input id="resource-name" required placeholder="A resource worth sharing"><label for="resource-url">Website URL</label><input id="resource-url" type="url" required placeholder="https://"><button class="primary">Save suggestion</button><small>Prototype: saved in this browser only. Nothing is sent.</small></form>';dialog.showModal();$('#submission').onsubmit=e=>{e.preventDefault();try{const saved=JSON.parse(localStorage.getItem('uilist-suggestions')||'[]');saved.push({name:$('#resource-name').value,url:$('#resource-url').value});localStorage.setItem('uilist-suggestions',JSON.stringify(saved));content.innerHTML='<h2>Suggestion saved.</h2><p>It’s saved in this browser for later. Thanks for adding to the collection.</p>'}catch{content.innerHTML='<h2>Couldn’t save just now.</h2><p>Browser storage is unavailable. Nothing has been sent.</p>'}}};render();
