import React, {useState, useRef, useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Grid2X2,Heart,Layers,Box,Shapes,Image,Lightbulb,Search,Sun,Moon,PanelLeft,X,Plus,Bookmark,BookmarkCheck,ArrowUpRight,PanelsTopLeft,PenTool,Type,RectangleVertical,Store,ChevronDown} from 'lucide-react';
import {AnimatedSidebar,AnimatedSidebarClose,AnimatedSidebarContent,AnimatedSidebarFooter,AnimatedSidebarGroup,AnimatedSidebarGroupContent,AnimatedSidebarGroupLabel,AnimatedSidebarHeader,AnimatedSidebarInset,AnimatedSidebarMenu,AnimatedSidebarMenuButton,AnimatedSidebarMenuItem,AnimatedSidebarMenuSub,AnimatedSidebarMenuSubButton,AnimatedSidebarMenuSubItem,AnimatedSidebarProvider,AnimatedSidebarRail,AnimatedSidebarTrigger} from './components/motion/animated-sidebar';
import {resources,categories,formats} from './data';
import './styles.css';
const icons=[Layers,Box,PanelsTopLeft,Shapes,Image,PenTool,Type,RectangleVertical,Lightbulb,Store];
function load<T,>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function App(){
 const [page,setPage]=useState('all'),[category,setCategory]=useState<string|null>(null),[sub,setSub]=useState<string|null>(null),[openSection,setOpenSection]=useState<string|null>('Templates'),[search,setSearch]=useState(''),[price,setPrice]=useState('All'),[saved,setSaved]=useState<string[]>(()=>load('uilist-favourites',[])),[light,setLight]=useState(false),[sidebarOpen,setSidebarOpen]=useState(true),[mobileOpen,setMobileOpen]=useState(false),[modal,setModal]=useState<string|null>(null),[submitted,setSubmitted]=useState(false);
 const [browse,setBrowse]=useState('Featured'),[format,setFormat]=useState('All formats');
 const dialog=useRef<HTMLDialogElement>(null),searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{localStorage.setItem('uilist-favourites',JSON.stringify(saved))}catch{}},[saved]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',!light);document.documentElement.classList.toggle('light',light)},[light]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='/'&&!modal&&!mobileOpen&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();searchRef.current?.focus()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[modal,mobileOpen]);
 const reset=()=>{setPage('all');setCategory(null);setSub(null);setSearch('');setPrice('All');setFormat('All formats');setBrowse('Featured')};
 const choosePage=(next:string)=>{setPage(next);setCategory(null);setSub(null);setOpenSection(null)};
 const chooseCategory=(name:string)=>{setCategory(name);setSub(null);setOpenSection(current=>current===name?null:name)};
 const toggleSaved=(id:string)=>setSaved(current=>current.includes(id)?current.filter(s=>s!==id):[...current,id]);
 const shown=resources.filter(r=>(page!=='saved'||saved.includes(r.id))&&(!category||r.category===category||r.tags.includes(category))&&(!sub||r.subcategory===sub||r.tags.includes(sub))&&(price==='All'||r.access.includes(price))&&(format==='All formats'||r.formats.includes(format))&&(browse!=='Featured'||r.featured||Boolean(category)||page==='saved')&&[r.name,r.creator,...r.formats,r.category,r.subcategory,...r.tags].join(' ').toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>browse==='Recent'?b.addedOrder-a.addedOrder:a.addedOrder-b.addedOrder);
 const title=sub||category||(page==='saved'?'Favourites':'All websites');
 return <AnimatedSidebarProvider open={sidebarOpen} onOpenChange={setSidebarOpen} openMobile={mobileOpen} onOpenMobileChange={setMobileOpen} style={{'--sidebar-width':'15.25rem','--sidebar-width-icon':'4.25rem'}}>
 <AnimatedSidebar ariaLabel="UIXO navigation" collapsible="icon">
  <AnimatedSidebarHeader className="p-3 pb-2"><div className="flex min-h-11 items-center gap-3 overflow-hidden px-2"><a href="/" aria-label="UIXO home" className="brand"><span className="group-data-[state=collapsed]/sidebar:hidden">UIXO</span><span className="hidden group-data-[state=collapsed]/sidebar:block">U</span></a><AnimatedSidebarTrigger className="sidebar-header-toggle ml-auto hidden md:grid" aria-label="Toggle navigation"><PanelLeft className="size-4"/></AnimatedSidebarTrigger><AnimatedSidebarClose className="ml-auto md:hidden"><X className="size-4"/></AnimatedSidebarClose></div></AnimatedSidebarHeader>
  <AnimatedSidebarContent className="px-2 pt-1">
   <AnimatedSidebarGroup className="pb-5 pt-5"><AnimatedSidebarGroupContent><AnimatedSidebarMenu>
    <AnimatedSidebarMenuItem><AnimatedSidebarMenuButton icon={<Grid2X2 className="size-4"/>} badge={String(resources.length)} isActive={page==='all'&&!category} onSelect={()=>choosePage('all')}>All websites</AnimatedSidebarMenuButton></AnimatedSidebarMenuItem>
    <AnimatedSidebarMenuItem><AnimatedSidebarMenuButton icon={<Heart className="size-4"/>} badge={String(saved.length)} isActive={page==='saved'&&!category} onSelect={()=>choosePage('saved')}>Favourites</AnimatedSidebarMenuButton></AnimatedSidebarMenuItem>
   </AnimatedSidebarMenu></AnimatedSidebarGroupContent></AnimatedSidebarGroup>
   <AnimatedSidebarGroup className="border-t border-border pt-4"><AnimatedSidebarGroupLabel>Categories</AnimatedSidebarGroupLabel><AnimatedSidebarGroupContent><AnimatedSidebarMenu>
   {categories.map((c,i)=>{const Icon=icons[i];return <AnimatedSidebarMenuItem key={c.name}><AnimatedSidebarMenuButton icon={<Icon className="size-4"/>} isActive={category===c.name} ariaExpanded={openSection===c.name} onSelect={()=>chooseCategory(c.name)}>{c.name}</AnimatedSidebarMenuButton><AnimatedSidebarMenuSub open={openSection===c.name}>{c.sub.map(child=><AnimatedSidebarMenuSubItem key={child}><AnimatedSidebarMenuSubButton isActive={category===c.name&&sub===child} onSelect={()=>{setCategory(c.name);setSub(child)}}>{child}</AnimatedSidebarMenuSubButton></AnimatedSidebarMenuSubItem>)}</AnimatedSidebarMenuSub></AnimatedSidebarMenuItem>})}
   </AnimatedSidebarMenu></AnimatedSidebarGroupContent></AnimatedSidebarGroup>
  </AnimatedSidebarContent>
  <AnimatedSidebarFooter className="gap-3 border-none p-3"><AnimatedSidebarMenu><AnimatedSidebarMenuItem><AnimatedSidebarMenuButton icon={<Plus className="size-4"/>} onSelect={()=>{setSubmitted(false);setModal('submit')}}>Submit a website</AnimatedSidebarMenuButton></AnimatedSidebarMenuItem></AnimatedSidebarMenu><p className="sidebar-note group-data-[state=collapsed]/sidebar:hidden">Curated for the curious.<br/>A little corner of the internet.</p></AnimatedSidebarFooter><AnimatedSidebarRail/>
 </AnimatedSidebar>
 <AnimatedSidebarInset className="site-main">
  <header className="topbar"><AnimatedSidebarTrigger className="utility mobile-sidebar-trigger" aria-label="Open navigation"><PanelLeft className="size-4"/></AnimatedSidebarTrigger><div className="search-wrap"><Search size={16}/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} type="search" aria-label="Search websites" placeholder="Search websites…"/><kbd>/</kbd></div><div className="segments prices" role="group" aria-label="Pricing">{['All','Free','Paid'].map(p=><button key={p} className={price===p?'selected':''} aria-pressed={price===p} onClick={()=>setPrice(p)}>{p}</button>)}</div><nav className="top-nav" aria-label="Main navigation"><button className="selected" onClick={reset}>Explore</button><button onClick={()=>setModal('collections')}>Collections</button><button onClick={()=>setModal('about')}>About</button></nav><button className="utility theme" onClick={()=>setLight(!light)} aria-label={`Switch to ${light?'dark':'light'} theme`}>{light?<Moon size={18}/>:<Sun size={18}/>}</button></header>
  <section className="heading"><div><h1>{title}</h1><p>{page==='saved'?'The good ones, kept close.':'Good tools. Great interfaces.'}</p></div>{(search||category||price!=='All'||format!=='All formats')&&<button className="clear" onClick={()=>{setSearch('');setCategory(null);setSub(null);setPrice('All');setFormat('All formats')}}>Clear filters <X size={12}/></button>}</section>
  <div className="discovery-toolbar"><div className="segments browse-tabs" role="group" aria-label="Browse order">{['Featured','Recent'].map(tab=><button key={tab} className={browse===tab?'selected':''} aria-pressed={browse===tab} onClick={()=>setBrowse(tab)}>{tab}</button>)}</div><label className="format-filter"><span>Format:</span><select aria-label="Resource format" value={format} onChange={e=>setFormat(e.target.value)}><option>All formats</option>{formats.map(f=><option key={f}>{f}</option>)}</select><ChevronDown size={13}/></label></div>
  <section className="website-grid" aria-label="Websites">{shown.map(r=><article key={r.id}><a className="preview-link" href={r.url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${r.name}`}><img src={`/assets/${r.id}.png`} alt={`${r.name} website preview`}/></a><div className="card-heading"><a href={r.url} target="_blank" rel="noopener noreferrer">{r.name}</a><button className="save" aria-label={`${saved.includes(r.id)?'Remove':'Save'} ${r.name} ${saved.includes(r.id)?'from':'to'} favourites`} aria-pressed={saved.includes(r.id)} onClick={()=>toggleSaved(r.id)}>{saved.includes(r.id)?<BookmarkCheck size={18}/>:<Bookmark size={18}/>}</button></div><div className="metadata"><span>by {r.creator}</span><span>·</span><span>{r.access.join(' + ')}</span></div><div className="resource-tags"><button onClick={()=>{setCategory(r.category);setSub(null);setOpenSection(r.category)}}>{r.category}</button><button onClick={()=>setFormat(r.formats[0])}>{r.formats[0]}</button></div></article>)}</section>
  {!shown.length&&<section className="empty"><Search size={26}/><h2>Nothing here just yet.</h2><p>{page==='saved'&&!saved.length?'Tap a bookmark to keep a website here.':'Try another search, category, format, or pricing filter.'}</p><button onClick={reset}>Show all websites</button></section>}
  <footer className="site-footer"><span>{shown.length} website{shown.length===1?'':'s'}</span><span>Handpicked, not scraped.</span></footer>
 </AnimatedSidebarInset>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current){const b=dialog.current.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)setModal(null)}}}><button className="dialog-close utility" onClick={()=>setModal(null)} aria-label="Close dialog"><X size={17}/></button>{modal==='about'?<><h2>Good tools.<br/>Great interfaces.</h2><p>UIXO is a small, curated collection of websites for people who design and build.</p><p>Your favourites stay in this browser.</p></>:modal==='collections'?<><h2>A good place to start.</h2><p>Explore a corner of the collection.</p>{categories.map(c=><button key={c.name} className="collection" onClick={()=>{choosePage('all');chooseCategory(c.name);setSearch('');setPrice('All');setFormat('All formats');setModal(null)}}>{c.name}<ArrowUpRight size={16}/></button>)}</>:submitted?<><h2>Suggestion saved.</h2><p>It’s saved in this browser for later.</p></>:<><h2>Found something good?</h2><p>Keep a suggestion for the collection.</p><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);try{localStorage.setItem('uilist-suggestions',JSON.stringify([...load<any[]>('uilist-suggestions',[]),{name:data.get('name'),url:data.get('url')}]));setSubmitted(true)}catch{alert('Browser storage is unavailable. Nothing was sent.')}}}><label>Website name<input name="name" required placeholder="A resource worth sharing"/></label><label>Website URL<input name="url" type="url" required placeholder="https://"/></label><button className="primary">Save suggestion</button><small>Prototype: saved in this browser only. Nothing is sent.</small></form></>}</dialog>
 </AnimatedSidebarProvider>
}
createRoot(document.getElementById('root')!).render(<App/>);
